# Generated by Django 5.2.8 on 2025-12-20 03:29

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budgettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpre',
            name='uploaded_excel_file',
            field=models.FileField(blank=True, help_text='Upload PRE Excel file', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pre_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
    ]
