# Generated by Django 5.2.8 on 2025-12-20 03:32

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_departmentpre_uploaded_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpresupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file (PDF, Word, Excel, Images)', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pre_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
