# Generated by Django 5.2.8 on 2025-12-20 05:25

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_departmentpresupportingdocument_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PREDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_excel_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pre_drafts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('pre_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_drafts', to='budgets.budgetallocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PRE Draft',
                'verbose_name_plural': 'PRE Drafts',
                'db_table': 'pre_drafts',
            },
        ),
        migrations.CreateModel(
            name='PREDraftSupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pre_draft_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budgets.predraft')),
            ],
            options={
                'verbose_name': 'PRE Draft Supporting Document',
                'db_table': 'pre_draft_supporting_documents',
            },
        ),
    ]
