# Generated by Django 5.2.8 on 2026-01-09 12:01

import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_predraft_predraftsupportingdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='archive_type',
            field=models.CharField(blank=True, choices=[('FISCAL_YEAR', 'Fiscal Year Archive'), ('MANUAL', 'Manual Archive/Delete')], default='FISCAL_YEAR', max_length=20),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_pre_realignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prebudgetrealignment',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='activitydesign',
            name='uploaded_document',
            field=models.FileField(help_text='Upload Activity Design document (.docx format)', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='ad_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='activitydesignsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='ad_supporting_docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='prdraft',
            name='pr_file',
            field=models.FileField(blank=True, help_text='Uploaded PR document', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pr_drafts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='prdraftsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pr_draft_supporting/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='uploaded_document',
            field=models.FileField(blank=True, help_text='Uploaded PR document', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pr_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequestapproveddocument',
            name='document',
            field=models.FileField(help_text='Signed/approved document (PDF or image scan)', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pr_signed_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequestsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pr_supporting_docs/%Y/%m/'),
        ),
    ]
