# Generated by Django 5.2.8 on 2026-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_prebudgetrealignment_archive_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettransaction',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
