# Generated by Django 5.2.8 on 2026-03-12 09:16

import apps.budgets.models
import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_alter_budgettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document (PDF, Word, Excel)', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=apps.budgets.models.supporting_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls'])]),
        ),
    ]
