# Generated by Django 5.2.8 on 2026-03-16 02:43

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_alter_supportingdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrealignmentsupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF for image/office document uploads', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_converted_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='budgetrealignmentsupportingdocument',
            name='document',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
