# Generated by Django 5.2.8 on 2026-03-16 02:54

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_alter_budgetrealignmentsupportingdocument_converted_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='end_user_uploaded_document',
            field=models.FileField(blank=True, help_text='Signed document uploaded by end user after partial approval', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_end_user_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='final_approved_scan',
            field=models.FileField(blank=True, help_text='Scanned copy of signed budget realignment', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='PDF generated from uploaded documents when partially approved', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='br_pdfs/%Y/%m/'),
        ),
    ]
