# Generated by Django 5.2.8 on 2026-05-18 00:28

import apps.budgets.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_alter_prebudgetrealignment_approved_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydesign',
            name='uploaded_document',
            field=models.FileField(help_text='Upload Activity Design document (.docx format)', upload_to='ad_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='activitydesignsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file', upload_to='ad_supporting_docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='budgetrealignmentsupportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF for image/office document uploads', null=True, upload_to='br_converted_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='budgetrealignmentsupportingdocument',
            name='document',
            field=models.FileField(upload_to='br_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='departmentpre',
            name='uploaded_excel_file',
            field=models.FileField(blank=True, help_text='Upload PRE Excel file', null=True, upload_to='pre_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='departmentpresupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file (PDF, Word, Excel, Images)', upload_to='pre_supporting_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prdraft',
            name='pr_file',
            field=models.FileField(blank=True, help_text='Uploaded PR document', null=True, upload_to='pr_drafts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='prdraftsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document', upload_to='pr_draft_supporting/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='approved_documents',
            field=models.FileField(blank=True, help_text='Scanned approved documents uploaded by admin', null=True, upload_to='br_approved_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='end_user_uploaded_document',
            field=models.FileField(blank=True, help_text='Signed document uploaded by end user after partial approval', null=True, upload_to='br_end_user_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='final_approved_scan',
            field=models.FileField(blank=True, help_text='Scanned copy of signed budget realignment', null=True, upload_to='br_scanned/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='prebudgetrealignment',
            name='partially_approved_pdf',
            field=models.FileField(blank=True, help_text='PDF generated from uploaded documents when partially approved', null=True, upload_to='br_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='predraft',
            name='uploaded_excel_file',
            field=models.FileField(blank=True, null=True, upload_to='pre_drafts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])]),
        ),
        migrations.AlterField(
            model_name='predraftsupportingdocument',
            name='document',
            field=models.FileField(upload_to='pre_draft_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='uploaded_document',
            field=models.FileField(blank=True, help_text='Uploaded PR document', null=True, upload_to='pr_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'doc', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequestapproveddocument',
            name='document',
            field=models.FileField(help_text='Signed/approved document (PDF or image scan)', upload_to='pr_signed_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='purchaserequestsupportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document file', upload_to='pr_supporting_docs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='document',
            field=models.FileField(help_text='Supporting document (PDF, Word, Excel)', upload_to=apps.budgets.models.supporting_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'xlsx', 'xls'])]),
        ),
    ]
