# Generated by Django 5.2.8 on 2026-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_remove_cloudinary_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydesign',
            name='uploaded_document_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF of the uploaded document (generated on first preview)', null=True, upload_to='ad_converted_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='departmentpre',
            name='uploaded_excel_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF of the uploaded Excel file (generated on first preview)', null=True, upload_to='pre_converted_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='uploaded_document_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF of the uploaded document (generated on first preview)', null=True, upload_to='pr_converted_pdfs/%Y/%m/'),
        ),
    ]
