# Generated by Django 5.2.8 on 2026-05-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_add_converted_pdf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='converted_pdf',
            field=models.FileField(blank=True, help_text='Auto-converted PDF for office document uploads', null=True, upload_to='ab_converted_pdfs/%Y/%m/'),
        ),
    ]
